axios kub instance
oslabs-beta/podwatch pull request #6
Opened 2023-02-28 04:33 UTC by kmarrow1

2023-03-02 01:33 UTC, mashkn reviewed
In the main file, I wonder if we would need to check for null as well as undefined - for example, with an exclamation point in front of the variable name. This would be covering the case of the variable being defined in the env file but not actually having a value.

2023-03-02 02:56 UTC, kmarrow1 commented
> In the main file, I wonder if we would need to check for null as well as undefined - for example, with an exclamation point in front of the variable name. This would be covering the case of the variable being defined in the env file but not actually having a value.

Will fix! Good idea!

2023-03-03 02:19 UTC, WVAviator requested changes

2023-03-03 02:19 UTC, WVAviator commented on packages/watcher/src/axios-kub.ts
> +);
I think the cacert file should be fetched down alongside the KUBE_TOKEN declaration since it's not used when the service is outside the cluster. THis might throw an error since the cacert file doesn't exist unless the service is started by kubernetes

2023-03-03 02:19 UTC, WVAviator commented on packages/watcher/src/axios-kub.ts
> +        'Content-Type': 'applicaiton/json',
typo in "application"

2023-03-03 02:23 UTC, kmarrow1 commented on packages/watcher/src/axios-kub.ts
> +);
Good catch moved this into the else if statement for if it is inside the cluster

2023-03-03 02:23 UTC, kmarrow1 commented on packages/watcher/src/axios-kub.ts
> +        'Content-Type': 'applicaiton/json',
Appreciate!!

2023-03-03 02:25 UTC, WVAviator approved these changes

2023-03-03 02:42 UTC, Hidinkyu approved these changes
I can understand now!

2023-03-03 02:42 UTC, merged